# flake8: noqa

"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


__version__ = "8.22.2"

# import ApiClient
from routing.api_client import ApiClient

# import Configuration
from routing.configuration import Configuration

# import exceptions
from routing.exceptions import OpenApiException
from routing.exceptions import ApiAttributeError
from routing.exceptions import ApiTypeError
from routing.exceptions import ApiValueError
from routing.exceptions import ApiKeyError
from routing.exceptions import ApiException
