"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from routing.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from routing.exceptions import ApiAttributeError



class Avoid(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'features': (str,),  # noqa: E501
            'areas': (str,),  # noqa: E501
            'segments': (str,),  # noqa: E501
            'zone_categories': (str,),  # noqa: E501
            'zone_identifiers': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'features': 'features',  # noqa: E501
        'areas': 'areas',  # noqa: E501
        'segments': 'segments',  # noqa: E501
        'zone_categories': 'zoneCategories',  # noqa: E501
        'zone_identifiers': 'zoneIdentifiers',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Avoid - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            features (str): A comma separated list of features that routes will avoid.  * `seasonalClosure` * `tollRoad` * `controlledAccessHighway` * `ferry` * `carShuttleTrain` * `tunnel` * `dirtRoad` * `difficultTurns` . [optional]  # noqa: E501
            areas (str): A pipe separated list of user defined areas that routes will avoid to go through.  Format: `{shape1}|{shape2}|{shape3}...`  Supported shape format: * Bounding box - A rectangular area on earth defined by a comma separated list of two latitude and two longitude values.   - Format: `bbox:{west},{south},{east},{north}`     + `{west}`  - Longitude value of the westernmost point of the area.     + `{south}` - Latitude value of the southernmost point of the area.     + `{east}`  - Longitude value of the easternmost point of the area.     + `{north}` - Latitude value of the northernmost point of the area.   - Example: `bbox:13.082,52.416,13.628,52.626` - Bounding box of Berlin . [optional]  # noqa: E501
            segments (str): A comma separated list of segment identifiers that routes will avoid going through.  Each entry has the following structure: `{segmentId}(#{direction})?`  The individual parts are: * segmentId: The identifier of the referenced topology segment inside the catalog, example: `here:cm:segment:207551710` * direction (optional): Either '*' for bidirectional (default), '+' for positive direction, or '-' for negative direction  Example of a parameter value excluding two segments: `here:cm:segment:207551710#+,here:cm:segment:76771992#*` . [optional]  # noqa: E501
            zone_categories (str): Specifies a list of categories of zones which routes will avoid going through.  Format: `Categories[ZoneCategoryOptions]`  * Categories: `{cat1},{cat2}...`   A comma separated list of zone categories. * ZoneCategoriesOptions (optional): `;option1=value1;options2=value2...`   A list of options for zone categories in `KEY=VALUE` form.  Supported zone category options:   * exceptZoneIds: A comma-separated list of zone identifiers, which will not be taken into account for evaluation of zone categories to avoid.  Supported zone categories:   * `vignette`   * `congestionPricing`   * `environmental`  Example of zone categories avoidance: `avoid[zoneCategories]=environmental,vignette`  Example of zone categories avoidance with exceptions: `avoid[zoneCategories]=environmental,vignette;exceptZoneIds=here:cm:envzone:3` . [optional]  # noqa: E501
            zone_identifiers (str): A comma separated list containing identifiers of zones that routes will avoid going through.  Example of an identifier referencing an environmental zone: `here:cm:envzone:2` . [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Avoid - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            features (str): A comma separated list of features that routes will avoid.  * `seasonalClosure` * `tollRoad` * `controlledAccessHighway` * `ferry` * `carShuttleTrain` * `tunnel` * `dirtRoad` * `difficultTurns` . [optional]  # noqa: E501
            areas (str): A pipe separated list of user defined areas that routes will avoid to go through.  Format: `{shape1}|{shape2}|{shape3}...`  Supported shape format: * Bounding box - A rectangular area on earth defined by a comma separated list of two latitude and two longitude values.   - Format: `bbox:{west},{south},{east},{north}`     + `{west}`  - Longitude value of the westernmost point of the area.     + `{south}` - Latitude value of the southernmost point of the area.     + `{east}`  - Longitude value of the easternmost point of the area.     + `{north}` - Latitude value of the northernmost point of the area.   - Example: `bbox:13.082,52.416,13.628,52.626` - Bounding box of Berlin . [optional]  # noqa: E501
            segments (str): A comma separated list of segment identifiers that routes will avoid going through.  Each entry has the following structure: `{segmentId}(#{direction})?`  The individual parts are: * segmentId: The identifier of the referenced topology segment inside the catalog, example: `here:cm:segment:207551710` * direction (optional): Either '*' for bidirectional (default), '+' for positive direction, or '-' for negative direction  Example of a parameter value excluding two segments: `here:cm:segment:207551710#+,here:cm:segment:76771992#*` . [optional]  # noqa: E501
            zone_categories (str): Specifies a list of categories of zones which routes will avoid going through.  Format: `Categories[ZoneCategoryOptions]`  * Categories: `{cat1},{cat2}...`   A comma separated list of zone categories. * ZoneCategoriesOptions (optional): `;option1=value1;options2=value2...`   A list of options for zone categories in `KEY=VALUE` form.  Supported zone category options:   * exceptZoneIds: A comma-separated list of zone identifiers, which will not be taken into account for evaluation of zone categories to avoid.  Supported zone categories:   * `vignette`   * `congestionPricing`   * `environmental`  Example of zone categories avoidance: `avoid[zoneCategories]=environmental,vignette`  Example of zone categories avoidance with exceptions: `avoid[zoneCategories]=environmental,vignette;exceptZoneIds=here:cm:envzone:3` . [optional]  # noqa: E501
            zone_identifiers (str): A comma separated list containing identifiers of zones that routes will avoid going through.  Example of an identifier referencing an environmental zone: `here:cm:envzone:2` . [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
