"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from routing.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from routing.exceptions import ApiAttributeError


def lazy_import():
    from routing.model.agency import Agency
    from routing.model.attribution import Attribution
    from routing.model.fare import Fare
    from routing.model.notice import Notice
    from routing.model.offset_action import OffsetAction
    from routing.model.passthrough import Passthrough
    from routing.model.pedestrian_section import PedestrianSection
    from routing.model.routing_zone import RoutingZone
    from routing.model.toll_cost import TollCost
    from routing.model.transit_departure import TransitDeparture
    from routing.model.transit_incident import TransitIncident
    from routing.model.transit_post_action import TransitPostAction
    from routing.model.transit_pre_action import TransitPreAction
    from routing.model.transit_section import TransitSection
    from routing.model.transit_span import TransitSpan
    from routing.model.transit_stop import TransitStop
    from routing.model.transit_transport import TransitTransport
    from routing.model.vehicle_section import VehicleSection
    from routing.model.web_link import WebLink
    globals()['Agency'] = Agency
    globals()['Attribution'] = Attribution
    globals()['Fare'] = Fare
    globals()['Notice'] = Notice
    globals()['OffsetAction'] = OffsetAction
    globals()['Passthrough'] = Passthrough
    globals()['PedestrianSection'] = PedestrianSection
    globals()['RoutingZone'] = RoutingZone
    globals()['TollCost'] = TollCost
    globals()['TransitDeparture'] = TransitDeparture
    globals()['TransitIncident'] = TransitIncident
    globals()['TransitPostAction'] = TransitPostAction
    globals()['TransitPreAction'] = TransitPreAction
    globals()['TransitSection'] = TransitSection
    globals()['TransitSpan'] = TransitSpan
    globals()['TransitStop'] = TransitStop
    globals()['TransitTransport'] = TransitTransport
    globals()['VehicleSection'] = VehicleSection
    globals()['WebLink'] = WebLink


class RouterSection(ModelComposed):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'type': (str,),  # noqa: E501
            'pre_actions': ([TransitPreAction],),  # noqa: E501
            'actions': ([OffsetAction],),  # noqa: E501
            'language': (str,),  # noqa: E501
            'post_actions': ([TransitPostAction],),  # noqa: E501
            'turn_by_turn_actions': ([OffsetAction],),  # noqa: E501
            'passthrough': ([Passthrough],),  # noqa: E501
            'summary': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'travel_summary': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
            'polyline': (str,),  # noqa: E501
            'notices': ([Notice],),  # noqa: E501
            'spans': ([TransitSpan],),  # noqa: E501
            'routing_zones': ([RoutingZone],),  # noqa: E501
            'incidents': ([TransitIncident],),  # noqa: E501
            'ref_replacements': ({str: (str,)},),  # noqa: E501
            'tolls': ([TollCost],),  # noqa: E501
            'intermediate_stops': ([TransitStop],),  # noqa: E501
            'agency': (Agency,),  # noqa: E501
            'attributions': ([Attribution],),  # noqa: E501
            'fares': ([Fare],),  # noqa: E501
            'booking': (WebLink,),  # noqa: E501
            'id': (str,),  # noqa: E501
            'departure': (TransitDeparture,),  # noqa: E501
            'arrival': (TransitDeparture,),  # noqa: E501
            'transport': (TransitTransport,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        lazy_import()
        val = {
            'PedestrianSection': PedestrianSection,
            'TransitSection': TransitSection,
            'VehicleSection': VehicleSection,
            'pedestrian': PedestrianSection,
            'transit': TransitSection,
            'vehicle': VehicleSection,
        }
        if not val:
            return None
        return {'type': val}

    attribute_map = {
        'type': 'type',  # noqa: E501
        'pre_actions': 'preActions',  # noqa: E501
        'actions': 'actions',  # noqa: E501
        'language': 'language',  # noqa: E501
        'post_actions': 'postActions',  # noqa: E501
        'turn_by_turn_actions': 'turnByTurnActions',  # noqa: E501
        'passthrough': 'passthrough',  # noqa: E501
        'summary': 'summary',  # noqa: E501
        'travel_summary': 'travelSummary',  # noqa: E501
        'polyline': 'polyline',  # noqa: E501
        'notices': 'notices',  # noqa: E501
        'spans': 'spans',  # noqa: E501
        'routing_zones': 'routingZones',  # noqa: E501
        'incidents': 'incidents',  # noqa: E501
        'ref_replacements': 'refReplacements',  # noqa: E501
        'tolls': 'tolls',  # noqa: E501
        'intermediate_stops': 'intermediateStops',  # noqa: E501
        'agency': 'agency',  # noqa: E501
        'attributions': 'attributions',  # noqa: E501
        'fares': 'fares',  # noqa: E501
        'booking': 'booking',  # noqa: E501
        'id': 'id',  # noqa: E501
        'departure': 'departure',  # noqa: E501
        'arrival': 'arrival',  # noqa: E501
        'transport': 'transport',  # noqa: E501
    }

    read_only_vars = {
    }

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """RouterSection - a model defined in OpenAPI

        Keyword Args:
            type (str): Section type used by the client to identify what extension to the BaseSection are available.
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            pre_actions ([TransitPreAction]): Actions that must be done prior to `departure`.. [optional]  # noqa: E501
            actions ([OffsetAction]): Actions that must be done during the travel portion of the section, i.e., between `departure` and `arrival`.. [optional]  # noqa: E501
            language (str): Language of the localized strings in the section, if any, in BCP47 format.. [optional]  # noqa: E501
            post_actions ([TransitPostAction]): Actions that must be done after `arrival`.. [optional]  # noqa: E501
            turn_by_turn_actions ([OffsetAction]): Actions for turn by turn guidance during the travel portion of the section, i.e., between `departure` and `arrival`.. [optional]  # noqa: E501
            passthrough ([Passthrough]): List of via waypoints this section is passing through.  Each via waypoint of the request that is a `passThrough=true` waypoint, appears as a `Passthrough` in the response. It appears in the section that starts with the closest non-passthrough via specified before it or origin.  The passthrough vias appear in this list in the order they are traversed. They are traversed in the order they are specified in the request. . [optional]  # noqa: E501
            summary (bool, date, datetime, dict, float, int, list, str, none_type): Total value of key attributes (e.g., duration, length) summed up for the entire section, including `preActions`, `postActions`, and the travel portion of the section. . [optional]  # noqa: E501
            travel_summary (bool, date, datetime, dict, float, int, list, str, none_type): Total value of key attributes (e.g., duration, length) summed up for just the travel portion of the section, between `departure` and `arrival`. `preActions` and `postActions` are excluded. . [optional]  # noqa: E501
            polyline (str): Line string in [Flexible Polyline](https://github.com/heremaps/flexible-polyline) format.. [optional]  # noqa: E501
            notices ([Notice]): Contains a list of issues related to this section of the route.  Follows a list of possible notice codes:  * `noSchedule`: A timetable schedule is not available for the transit line in this section,   and only the run frequency is available. As a result, departure/arrival times are approximated. * `noIntermediate`: Information about intermediate stops is not available for this transit line. * `unwantedMode`: This section contains a transport mode that was explictly disabled.   Mode filtering is not available in this area. * `scheduledTimes`: The times returned on this section are the scheduled times even though delay information are available. * `simplePolyline`: An accurate polyline is not available for this transit line. The returned polyline connects consecutive stops of a route with straight lines. . [optional]  # noqa: E501
            spans ([TransitSpan]): Span attached to a `Section` describing transit content. . [optional]  # noqa: E501
            routing_zones ([RoutingZone]): A list of routing zones that are applicable to the section.  Elements of this list will be referenced by indices within the `span` attribute of the section. . [optional]  # noqa: E501
            incidents ([TransitIncident]): A list of all incidents that apply to the section.. [optional]  # noqa: E501
            ref_replacements ({str: (str,)}): Dictionary of placeholders to replacement strings for the compact representation of map entity references. . [optional]  # noqa: E501
            tolls ([TollCost]): Detail of tolls to be paid for traversing this section. . [optional]  # noqa: E501
            intermediate_stops ([TransitStop]): Intermediate stops between departure and destination of the transit line. It can be missing if this information is not available or not requested. . [optional]  # noqa: E501
            agency (Agency): [optional]  # noqa: E501
            attributions ([Attribution]): List of required attributions to display.. [optional]  # noqa: E501
            fares ([Fare]): List of tickets to pay for this section of the route. [optional]  # noqa: E501
            booking (WebLink): [optional]  # noqa: E501
            id (str): Unique identifier of the section. [optional]  # noqa: E501
            departure (TransitDeparture): [optional]  # noqa: E501
            arrival (TransitDeparture): [optional]  # noqa: E501
            transport (TransitTransport): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        composed_info = validate_get_composed_info(
            constant_args, kwargs, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        discarded_args = composed_info[3]

        for var_name, var_value in kwargs.items():
            if var_name in discarded_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)

        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
        '_composed_instances',
        '_var_name_to_model_instances',
        '_additional_properties_model_instances',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """RouterSection - a model defined in OpenAPI

        Keyword Args:
            type (str): Section type used by the client to identify what extension to the BaseSection are available.
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            pre_actions ([TransitPreAction]): Actions that must be done prior to `departure`.. [optional]  # noqa: E501
            actions ([OffsetAction]): Actions that must be done during the travel portion of the section, i.e., between `departure` and `arrival`.. [optional]  # noqa: E501
            language (str): Language of the localized strings in the section, if any, in BCP47 format.. [optional]  # noqa: E501
            post_actions ([TransitPostAction]): Actions that must be done after `arrival`.. [optional]  # noqa: E501
            turn_by_turn_actions ([OffsetAction]): Actions for turn by turn guidance during the travel portion of the section, i.e., between `departure` and `arrival`.. [optional]  # noqa: E501
            passthrough ([Passthrough]): List of via waypoints this section is passing through.  Each via waypoint of the request that is a `passThrough=true` waypoint, appears as a `Passthrough` in the response. It appears in the section that starts with the closest non-passthrough via specified before it or origin.  The passthrough vias appear in this list in the order they are traversed. They are traversed in the order they are specified in the request. . [optional]  # noqa: E501
            summary (bool, date, datetime, dict, float, int, list, str, none_type): Total value of key attributes (e.g., duration, length) summed up for the entire section, including `preActions`, `postActions`, and the travel portion of the section. . [optional]  # noqa: E501
            travel_summary (bool, date, datetime, dict, float, int, list, str, none_type): Total value of key attributes (e.g., duration, length) summed up for just the travel portion of the section, between `departure` and `arrival`. `preActions` and `postActions` are excluded. . [optional]  # noqa: E501
            polyline (str): Line string in [Flexible Polyline](https://github.com/heremaps/flexible-polyline) format.. [optional]  # noqa: E501
            notices ([Notice]): Contains a list of issues related to this section of the route.  Follows a list of possible notice codes:  * `noSchedule`: A timetable schedule is not available for the transit line in this section,   and only the run frequency is available. As a result, departure/arrival times are approximated. * `noIntermediate`: Information about intermediate stops is not available for this transit line. * `unwantedMode`: This section contains a transport mode that was explictly disabled.   Mode filtering is not available in this area. * `scheduledTimes`: The times returned on this section are the scheduled times even though delay information are available. * `simplePolyline`: An accurate polyline is not available for this transit line. The returned polyline connects consecutive stops of a route with straight lines. . [optional]  # noqa: E501
            spans ([TransitSpan]): Span attached to a `Section` describing transit content. . [optional]  # noqa: E501
            routing_zones ([RoutingZone]): A list of routing zones that are applicable to the section.  Elements of this list will be referenced by indices within the `span` attribute of the section. . [optional]  # noqa: E501
            incidents ([TransitIncident]): A list of all incidents that apply to the section.. [optional]  # noqa: E501
            ref_replacements ({str: (str,)}): Dictionary of placeholders to replacement strings for the compact representation of map entity references. . [optional]  # noqa: E501
            tolls ([TollCost]): Detail of tolls to be paid for traversing this section. . [optional]  # noqa: E501
            intermediate_stops ([TransitStop]): Intermediate stops between departure and destination of the transit line. It can be missing if this information is not available or not requested. . [optional]  # noqa: E501
            agency (Agency): [optional]  # noqa: E501
            attributions ([Attribution]): List of required attributions to display.. [optional]  # noqa: E501
            fares ([Fare]): List of tickets to pay for this section of the route. [optional]  # noqa: E501
            booking (WebLink): [optional]  # noqa: E501
            id (str): Unique identifier of the section. [optional]  # noqa: E501
            departure (TransitDeparture): [optional]  # noqa: E501
            arrival (TransitDeparture): [optional]  # noqa: E501
            transport (TransitTransport): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        constant_args = {
            '_check_type': _check_type,
            '_path_to_item': _path_to_item,
            '_spec_property_naming': _spec_property_naming,
            '_configuration': _configuration,
            '_visited_composed_classes': self._visited_composed_classes,
        }
        composed_info = validate_get_composed_info(
            constant_args, kwargs, self)
        self._composed_instances = composed_info[0]
        self._var_name_to_model_instances = composed_info[1]
        self._additional_properties_model_instances = composed_info[2]
        discarded_args = composed_info[3]

        for var_name, var_value in kwargs.items():
            if var_name in discarded_args and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self._additional_properties_model_instances:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")

    @cached_property
    def _composed_schemas():
        # we need this here to make our import statements work
        # we must store _composed_schemas in here so the code is only run
        # when we invoke this method. If we kept this at the class
        # level we would get an error because the class level
        # code would be run when this module is imported, and these composed
        # classes don't exist yet because their module has not finished
        # loading
        lazy_import()
        return {
          'anyOf': [
          ],
          'allOf': [
          ],
          'oneOf': [
              PedestrianSection,
              TransitSection,
              VehicleSection,
          ],
        }
