"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from routing.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from routing.exceptions import ApiAttributeError


def lazy_import():
    from routing.model.truck_type_with_default import TruckTypeWithDefault
    from routing.model.tunnel_category import TunnelCategory
    globals()['TruckTypeWithDefault'] = TruckTypeWithDefault
    globals()['TunnelCategory'] = TunnelCategory


class Truck(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
        ('gross_weight',): {
            'inclusive_minimum': 0,
        },
        ('weight_per_axle',): {
            'inclusive_minimum': 0,
        },
        ('height',): {
            'inclusive_maximum': 5000,
            'inclusive_minimum': 0,
        },
        ('width',): {
            'inclusive_maximum': 5000,
            'inclusive_minimum': 0,
        },
        ('length',): {
            'inclusive_maximum': 30000,
            'inclusive_minimum': 0,
        },
        ('axle_count',): {
            'inclusive_maximum': 255,
            'inclusive_minimum': 2,
        },
        ('trailer_count',): {
            'inclusive_maximum': 255,
            'inclusive_minimum': 0,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'shipped_hazardous_goods': (str,),  # noqa: E501
            'gross_weight': (int,),  # noqa: E501
            'weight_per_axle': (int,),  # noqa: E501
            'height': (int,),  # noqa: E501
            'width': (int,),  # noqa: E501
            'length': (int,),  # noqa: E501
            'tunnel_category': (TunnelCategory,),  # noqa: E501
            'axle_count': (int,),  # noqa: E501
            'type': (TruckTypeWithDefault,),  # noqa: E501
            'trailer_count': (int,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'shipped_hazardous_goods': 'shippedHazardousGoods',  # noqa: E501
        'gross_weight': 'grossWeight',  # noqa: E501
        'weight_per_axle': 'weightPerAxle',  # noqa: E501
        'height': 'height',  # noqa: E501
        'width': 'width',  # noqa: E501
        'length': 'length',  # noqa: E501
        'tunnel_category': 'tunnelCategory',  # noqa: E501
        'axle_count': 'axleCount',  # noqa: E501
        'type': 'type',  # noqa: E501
        'trailer_count': 'trailerCount',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Truck - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            shipped_hazardous_goods (str): Comma-separated list of shipped hazardous goods in the vehicle.  Possible values are:  * `explosive`: Explosive material * `gas`: Gas * `flammable`: Flammable material * `combustible`: Combustible material * `organic`: Organic material * `poison`: Poison * `radioactive`: Radioactive material * `corrosive`: Corrosive material * `poisonousInhalation`: Materials that are poisonous upon inhalation * `harmfulToWater`: Materials that are harmful to water * `other`: Other types of hazardous materials . [optional]  # noqa: E501
            gross_weight (int): Vehicle weight including trailers and shipped goods, in kilograms.. [optional]  # noqa: E501
            weight_per_axle (int): Vehicle weight per axle, in kilograms.. [optional]  # noqa: E501
            height (int): Vehicle height, in centimeters.. [optional]  # noqa: E501
            width (int): Vehicle width, in centimeters.. [optional]  # noqa: E501
            length (int): Vehicle length, in centimeters.. [optional]  # noqa: E501
            tunnel_category (TunnelCategory): [optional]  # noqa: E501
            axle_count (int): Defines total number of axles in the vehicle. . [optional]  # noqa: E501
            type (TruckTypeWithDefault): [optional]  # noqa: E501
            trailer_count (int): Number of trailers attached to the vehicle.. [optional] if omitted the server will use the default value of 0  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Truck - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            shipped_hazardous_goods (str): Comma-separated list of shipped hazardous goods in the vehicle.  Possible values are:  * `explosive`: Explosive material * `gas`: Gas * `flammable`: Flammable material * `combustible`: Combustible material * `organic`: Organic material * `poison`: Poison * `radioactive`: Radioactive material * `corrosive`: Corrosive material * `poisonousInhalation`: Materials that are poisonous upon inhalation * `harmfulToWater`: Materials that are harmful to water * `other`: Other types of hazardous materials . [optional]  # noqa: E501
            gross_weight (int): Vehicle weight including trailers and shipped goods, in kilograms.. [optional]  # noqa: E501
            weight_per_axle (int): Vehicle weight per axle, in kilograms.. [optional]  # noqa: E501
            height (int): Vehicle height, in centimeters.. [optional]  # noqa: E501
            width (int): Vehicle width, in centimeters.. [optional]  # noqa: E501
            length (int): Vehicle length, in centimeters.. [optional]  # noqa: E501
            tunnel_category (TunnelCategory): [optional]  # noqa: E501
            axle_count (int): Defines total number of axles in the vehicle. . [optional]  # noqa: E501
            type (TruckTypeWithDefault): [optional]  # noqa: E501
            trailer_count (int): Number of trailers attached to the vehicle.. [optional] if omitted the server will use the default value of 0  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
