"""
    Geocoding and Search API v7

    This document describes the Geocoding and Search API.  # noqa: E501

    The version of the OpenAPI document: 7.74
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import geocoding
from geocoding.model.country_info import CountryInfo


class TestCountryInfo(unittest.TestCase):
    """CountryInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountryInfo(self):
        """Test CountryInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CountryInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
