"""
    Geocoding and Search API v7

    This document describes the Geocoding and Search API.  # noqa: E501

    The version of the OpenAPI document: 7.65
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import geocoding
from geocoding.model.open_search_reverse_geocode_response import OpenSearchReverseGeocodeResponse


class TestOpenSearchReverseGeocodeResponse(unittest.TestCase):
    """OpenSearchReverseGeocodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenSearchReverseGeocodeResponse(self):
        """Test OpenSearchReverseGeocodeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OpenSearchReverseGeocodeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
