"""
    Geocoding and Search API v7

    This document describes the Geocoding and Search API.  # noqa: E501

    The version of the OpenAPI document: 7.74
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import geocoding
from geocoding.model.street_info import StreetInfo


class TestStreetInfo(unittest.TestCase):
    """StreetInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreetInfo(self):
        """Test StreetInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StreetInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
