"""
    Geocoding and Search API v7

    This document describes the Geocoding and Search API.  # noqa: E501

    The version of the OpenAPI document: 7.65
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import geocoding
from geocoding.model.extended_attribute import ExtendedAttribute


class TestExtendedAttribute(unittest.TestCase):
    """ExtendedAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtendedAttribute(self):
        """Test ExtendedAttribute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExtendedAttribute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
