"""
    Geocoding and Search API v7

    This document describes the Geocoding and Search API.  # noqa: E501

    The version of the OpenAPI document: 7.65
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import geocoding
from geocoding.model.contact_information import ContactInformation


class TestContactInformation(unittest.TestCase):
    """ContactInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContactInformation(self):
        """Test ContactInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContactInformation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
