"""
    Geocoding and Search API v7

    This document describes the Geocoding and Search API.  # noqa: E501

    The version of the OpenAPI document: 7.65
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import geocoding
from geocoding.model.opening_hours import OpeningHours


class TestOpeningHours(unittest.TestCase):
    """OpeningHours unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpeningHours(self):
        """Test OpeningHours"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OpeningHours()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
