"""
    Geocoding and Search API v7

    This document describes the Geocoding and Search API.  # noqa: E501

    The version of the OpenAPI document: 7.65
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import geocoding
from geocoding.model.open_search_geocode_response import OpenSearchGeocodeResponse


class TestOpenSearchGeocodeResponse(unittest.TestCase):
    """OpenSearchGeocodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpenSearchGeocodeResponse(self):
        """Test OpenSearchGeocodeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OpenSearchGeocodeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
