# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from routing.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from routing.model.access_point_place import AccessPointPlace
from routing.model.agency import Agency
from routing.model.arrive_action import ArriveAction
from routing.model.attribution import Attribution
from routing.model.attribution_link_type import AttributionLinkType
from routing.model.auth_error_response_schema import AuthErrorResponseSchema
from routing.model.avoid import Avoid
from routing.model.avoid_post import AvoidPost
from routing.model.base_action import BaseAction
from routing.model.base_notice_detail import BaseNoticeDetail
from routing.model.base_place import BasePlace
from routing.model.base_summary import BaseSummary
from routing.model.board_action import BoardAction
from routing.model.calculate_routes_parameters import CalculateRoutesParameters
from routing.model.charging_action import ChargingAction
from routing.model.charging_connector_attributes import ChargingConnectorAttributes
from routing.model.charging_setup_action import ChargingSetupAction
from routing.model.charging_station_brand import ChargingStationBrand
from routing.model.charging_station_place import ChargingStationPlace
from routing.model.color import Color
from routing.model.continue_action import ContinueAction
from routing.model.data_version import DataVersion
from routing.model.deboard_action import DeboardAction
from routing.model.depart_action import DepartAction
from routing.model.distance import Distance
from routing.model.dynamic_speed_info import DynamicSpeedInfo
from routing.model.ev import EV
from routing.model.error_response import ErrorResponse
from routing.model.exclude import Exclude
from routing.model.exit_action import ExitAction
from routing.model.exit_info import ExitInfo
from routing.model.fare import Fare
from routing.model.fare_price import FarePrice
from routing.model.functional_class import FunctionalClass
from routing.model.get_routes_by_handle_parameters import GetRoutesByHandleParameters
from routing.model.health_response_fail_schema import HealthResponseFailSchema
from routing.model.health_response_ok_schema import HealthResponseOKSchema
from routing.model.keep_action import KeepAction
from routing.model.line_string import LineString
from routing.model.localized_string import LocalizedString
from routing.model.location import Location
from routing.model.match_trace import MatchTrace
from routing.model.match_trace_point import MatchTracePoint
from routing.model.max_speed import MaxSpeed
from routing.model.max_speed_one_of import MaxSpeedOneOf
from routing.model.model_return import ModelReturn
from routing.model.notice import Notice
from routing.model.notice_severity import NoticeSeverity
from routing.model.offset_action import OffsetAction
from routing.model.parking_lot_place import ParkingLotPlace
from routing.model.partial_time import PartialTime
from routing.model.passthrough import Passthrough
from routing.model.pedestrian_action import PedestrianAction
from routing.model.pedestrian_departure import PedestrianDeparture
from routing.model.pedestrian_place import PedestrianPlace
from routing.model.pedestrian_post_action import PedestrianPostAction
from routing.model.pedestrian_section import PedestrianSection
from routing.model.pedestrian_span import PedestrianSpan
from routing.model.pedestrian_speed import PedestrianSpeed
from routing.model.pedestrian_summary import PedestrianSummary
from routing.model.pedestrian_transport import PedestrianTransport
from routing.model.place import Place
from routing.model.ramp_action import RampAction
from routing.model.range_price import RangePrice
from routing.model.road_info import RoadInfo
from routing.model.road_info_type import RoadInfoType
from routing.model.roundabout_enter_action import RoundaboutEnterAction
from routing.model.roundabout_exit_action import RoundaboutExitAction
from routing.model.roundabout_pass_action import RoundaboutPassAction
from routing.model.route_response_notice import RouteResponseNotice
from routing.model.router_mode import RouterMode
from routing.model.router_route import RouterRoute
from routing.model.router_route_response import RouterRouteResponse
from routing.model.router_section import RouterSection
from routing.model.routing_error_response import RoutingErrorResponse
from routing.model.routing_mode import RoutingMode
from routing.model.routing_zone import RoutingZone
from routing.model.scooter import Scooter
from routing.model.single_price import SinglePrice
from routing.model.spans import Spans
from routing.model.speed import Speed
from routing.model.station_place import StationPlace
from routing.model.time_restricted_price import TimeRestrictedPrice
from routing.model.time_restricted_weekdays import TimeRestrictedWeekdays
from routing.model.toll_cost import TollCost
from routing.model.traffic_incident import TrafficIncident
from routing.model.traffic_incident_criticality import TrafficIncidentCriticality
from routing.model.trailer_count_range import TrailerCountRange
from routing.model.transit_departure import TransitDeparture
from routing.model.transit_incident import TransitIncident
from routing.model.transit_post_action import TransitPostAction
from routing.model.transit_pre_action import TransitPreAction
from routing.model.transit_section import TransitSection
from routing.model.transit_span import TransitSpan
from routing.model.transit_stop import TransitStop
from routing.model.transit_transport import TransitTransport
from routing.model.truck import Truck
from routing.model.truck_axle_count_range import TruckAxleCountRange
from routing.model.truck_type import TruckType
from routing.model.truck_type_with_default import TruckTypeWithDefault
from routing.model.tunnel_category import TunnelCategory
from routing.model.turn_action import TurnAction
from routing.model.turn_action_direction import TurnActionDirection
from routing.model.turn_action_severity import TurnActionSeverity
from routing.model.u_turn_action import UTurnAction
from routing.model.units import Units
from routing.model.vehicle import Vehicle
from routing.model.vehicle_action import VehicleAction
from routing.model.vehicle_departure import VehicleDeparture
from routing.model.vehicle_notice import VehicleNotice
from routing.model.vehicle_notice_detail import VehicleNoticeDetail
from routing.model.vehicle_place import VehiclePlace
from routing.model.vehicle_post_action import VehiclePostAction
from routing.model.vehicle_restriction import VehicleRestriction
from routing.model.vehicle_section import VehicleSection
from routing.model.vehicle_span import VehicleSpan
from routing.model.vehicle_summary import VehicleSummary
from routing.model.vehicle_transport import VehicleTransport
from routing.model.vehicle_travel_summary import VehicleTravelSummary
from routing.model.version_response import VersionResponse
from routing.model.web_link import WebLink
