"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.routing_mode import RoutingMode


class TestRoutingMode(unittest.TestCase):
    """RoutingMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoutingMode(self):
        """Test RoutingMode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoutingMode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
