"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.routing_error_response import RoutingErrorResponse


class TestRoutingErrorResponse(unittest.TestCase):
    """RoutingErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoutingErrorResponse(self):
        """Test RoutingErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoutingErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
