"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.distance import Distance
from routing.model.localized_string import LocalizedString
globals()['Distance'] = Distance
globals()['LocalizedString'] = LocalizedString
from routing.model.transit_span import TransitSpan


class TestTransitSpan(unittest.TestCase):
    """TransitSpan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransitSpan(self):
        """Test TransitSpan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransitSpan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
