"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.avoid_post import AvoidPost
globals()['AvoidPost'] = AvoidPost
from routing.model.calculate_routes_parameters import CalculateRoutesParameters


class TestCalculateRoutesParameters(unittest.TestCase):
    """CalculateRoutesParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCalculateRoutesParameters(self):
        """Test CalculateRoutesParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CalculateRoutesParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
