"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.distance import Distance
from routing.model.toll_cost import TollCost
globals()['Distance'] = Distance
globals()['TollCost'] = TollCost
from routing.model.vehicle_travel_summary import VehicleTravelSummary


class TestVehicleTravelSummary(unittest.TestCase):
    """VehicleTravelSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleTravelSummary(self):
        """Test VehicleTravelSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VehicleTravelSummary()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
