"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.exit_action import ExitAction
from routing.model.localized_string import LocalizedString
from routing.model.turn_action_direction import TurnActionDirection
from routing.model.turn_action_severity import TurnActionSeverity
globals()['ExitAction'] = ExitAction
globals()['LocalizedString'] = LocalizedString
globals()['TurnActionDirection'] = TurnActionDirection
globals()['TurnActionSeverity'] = TurnActionSeverity
from routing.model.roundabout_exit_action import RoundaboutExitAction


class TestRoundaboutExitAction(unittest.TestCase):
    """RoundaboutExitAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoundaboutExitAction(self):
        """Test RoundaboutExitAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoundaboutExitAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
