"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.localized_string import LocalizedString
from routing.model.turn_action import TurnAction
from routing.model.turn_action_direction import TurnActionDirection
from routing.model.turn_action_severity import TurnActionSeverity
globals()['LocalizedString'] = LocalizedString
globals()['TurnAction'] = TurnAction
globals()['TurnActionDirection'] = TurnActionDirection
globals()['TurnActionSeverity'] = TurnActionSeverity
from routing.model.roundabout_pass_action import RoundaboutPassAction


class TestRoundaboutPassAction(unittest.TestCase):
    """RoundaboutPassAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoundaboutPassAction(self):
        """Test RoundaboutPassAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoundaboutPassAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
