"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.offset_action import OffsetAction
globals()['OffsetAction'] = OffsetAction
from routing.model.continue_action import ContinueAction


class TestContinueAction(unittest.TestCase):
    """ContinueAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContinueAction(self):
        """Test ContinueAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContinueAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
