"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.route_response_notice import RouteResponseNotice
from routing.model.router_route import RouterRoute
globals()['RouteResponseNotice'] = RouteResponseNotice
globals()['RouterRoute'] = RouterRoute
from routing.model.router_route_response import RouterRouteResponse


class TestRouterRouteResponse(unittest.TestCase):
    """RouterRouteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRouterRouteResponse(self):
        """Test RouterRouteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RouterRouteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
