"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.scooter import Scooter


class TestScooter(unittest.TestCase):
    """Scooter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScooter(self):
        """Test Scooter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Scooter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
