"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.dynamic_speed_info import DynamicSpeedInfo


class TestDynamicSpeedInfo(unittest.TestCase):
    """DynamicSpeedInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDynamicSpeedInfo(self):
        """Test DynamicSpeedInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DynamicSpeedInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
