"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import routing
from routing.api.routing_api import RoutingApi  # noqa: E501


class TestRoutingApi(unittest.TestCase):
    """RoutingApi unit test stubs"""

    def setUp(self):
        self.api = RoutingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_calculate_routes(self):
        """Test case for calculate_routes

        Calculate routes via GET  # noqa: E501
        """
        pass

    def test_calculate_routes_post(self):
        """Test case for calculate_routes_post

        Calculate routes via POST  # noqa: E501
        """
        pass

    def test_get_routes_by_handle(self):
        """Test case for get_routes_by_handle

        Get route by handle  # noqa: E501
        """
        pass

    def test_get_routes_by_handle_post(self):
        """Test case for get_routes_by_handle_post

        Get route by handle via POST  # noqa: E501
        """
        pass

    def test_import_route(self):
        """Test case for import_route

        Calculate a route from a sequence of trace points  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
