"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import routing
from routing.api.common_api import CommonApi  # noqa: E501


class TestCommonApi(unittest.TestCase):
    """CommonApi unit test stubs"""

    def setUp(self):
        self.api = CommonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_health(self):
        """Test case for get_health

        Health status of the service  # noqa: E501
        """
        pass

    def test_get_version(self):
        """Test case for get_version

        Full version of the API  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
