"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.arrive_action import ArriveAction
from routing.model.continue_action import ContinueAction
from routing.model.depart_action import DepartAction
from routing.model.exit_action import ExitAction
from routing.model.keep_action import KeepAction
from routing.model.localized_string import LocalizedString
from routing.model.ramp_action import RampAction
from routing.model.roundabout_enter_action import RoundaboutEnterAction
from routing.model.roundabout_exit_action import RoundaboutExitAction
from routing.model.roundabout_pass_action import RoundaboutPassAction
from routing.model.turn_action import TurnAction
from routing.model.turn_action_direction import TurnActionDirection
from routing.model.turn_action_severity import TurnActionSeverity
from routing.model.u_turn_action import UTurnAction
globals()['ArriveAction'] = ArriveAction
globals()['ContinueAction'] = ContinueAction
globals()['DepartAction'] = DepartAction
globals()['ExitAction'] = ExitAction
globals()['KeepAction'] = KeepAction
globals()['LocalizedString'] = LocalizedString
globals()['RampAction'] = RampAction
globals()['RoundaboutEnterAction'] = RoundaboutEnterAction
globals()['RoundaboutExitAction'] = RoundaboutExitAction
globals()['RoundaboutPassAction'] = RoundaboutPassAction
globals()['TurnAction'] = TurnAction
globals()['TurnActionDirection'] = TurnActionDirection
globals()['TurnActionSeverity'] = TurnActionSeverity
globals()['UTurnAction'] = UTurnAction
from routing.model.pedestrian_action import PedestrianAction


class TestPedestrianAction(unittest.TestCase):
    """PedestrianAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPedestrianAction(self):
        """Test PedestrianAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PedestrianAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
