"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.base_action import BaseAction
from routing.model.notice import Notice
from routing.model.offset_action import OffsetAction
from routing.model.passthrough import Passthrough
from routing.model.pedestrian_action import PedestrianAction
from routing.model.pedestrian_departure import PedestrianDeparture
from routing.model.pedestrian_post_action import PedestrianPostAction
from routing.model.pedestrian_span import PedestrianSpan
from routing.model.pedestrian_transport import PedestrianTransport
globals()['BaseAction'] = BaseAction
globals()['Notice'] = Notice
globals()['OffsetAction'] = OffsetAction
globals()['Passthrough'] = Passthrough
globals()['PedestrianAction'] = PedestrianAction
globals()['PedestrianDeparture'] = PedestrianDeparture
globals()['PedestrianPostAction'] = PedestrianPostAction
globals()['PedestrianSpan'] = PedestrianSpan
globals()['PedestrianTransport'] = PedestrianTransport
from routing.model.pedestrian_section import PedestrianSection


class TestPedestrianSection(unittest.TestCase):
    """PedestrianSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPedestrianSection(self):
        """Test PedestrianSection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PedestrianSection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
