"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.charging_connector_attributes import ChargingConnectorAttributes
from routing.model.charging_station_brand import ChargingStationBrand
globals()['ChargingConnectorAttributes'] = ChargingConnectorAttributes
globals()['ChargingStationBrand'] = ChargingStationBrand
from routing.model.charging_station_place import ChargingStationPlace


class TestChargingStationPlace(unittest.TestCase):
    """ChargingStationPlace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChargingStationPlace(self):
        """Test ChargingStationPlace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ChargingStationPlace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
