"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.base_notice_detail import BaseNoticeDetail
from routing.model.notice_severity import NoticeSeverity
globals()['BaseNoticeDetail'] = BaseNoticeDetail
globals()['NoticeSeverity'] = NoticeSeverity
from routing.model.notice import Notice


class TestNotice(unittest.TestCase):
    """Notice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotice(self):
        """Test Notice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Notice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
