"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.localized_string import LocalizedString
from routing.model.road_info_type import RoadInfoType
globals()['LocalizedString'] = LocalizedString
globals()['RoadInfoType'] = RoadInfoType
from routing.model.road_info import RoadInfo


class TestRoadInfo(unittest.TestCase):
    """RoadInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoadInfo(self):
        """Test RoadInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RoadInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
