"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.base_place import BasePlace


class TestBasePlace(unittest.TestCase):
    """BasePlace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBasePlace(self):
        """Test BasePlace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BasePlace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
