"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.charging_action import ChargingAction
from routing.model.charging_setup_action import ChargingSetupAction
from routing.model.offset_action import OffsetAction
globals()['ChargingAction'] = ChargingAction
globals()['ChargingSetupAction'] = ChargingSetupAction
globals()['OffsetAction'] = OffsetAction
from routing.model.vehicle_post_action import VehiclePostAction


class TestVehiclePostAction(unittest.TestCase):
    """VehiclePostAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehiclePostAction(self):
        """Test VehiclePostAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VehiclePostAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
