"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.notice_severity import NoticeSeverity
from routing.model.vehicle_notice_detail import VehicleNoticeDetail
globals()['NoticeSeverity'] = NoticeSeverity
globals()['VehicleNoticeDetail'] = VehicleNoticeDetail
from routing.model.vehicle_notice import VehicleNotice


class TestVehicleNotice(unittest.TestCase):
    """VehicleNotice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleNotice(self):
        """Test VehicleNotice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VehicleNotice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
