"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.base_action import BaseAction
from routing.model.passthrough import Passthrough
from routing.model.routing_zone import RoutingZone
from routing.model.toll_cost import TollCost
from routing.model.traffic_incident import TrafficIncident
from routing.model.vehicle_action import VehicleAction
from routing.model.vehicle_departure import VehicleDeparture
from routing.model.vehicle_notice import VehicleNotice
from routing.model.vehicle_post_action import VehiclePostAction
from routing.model.vehicle_span import VehicleSpan
from routing.model.vehicle_transport import VehicleTransport
globals()['BaseAction'] = BaseAction
globals()['Passthrough'] = Passthrough
globals()['RoutingZone'] = RoutingZone
globals()['TollCost'] = TollCost
globals()['TrafficIncident'] = TrafficIncident
globals()['VehicleAction'] = VehicleAction
globals()['VehicleDeparture'] = VehicleDeparture
globals()['VehicleNotice'] = VehicleNotice
globals()['VehiclePostAction'] = VehiclePostAction
globals()['VehicleSpan'] = VehicleSpan
globals()['VehicleTransport'] = VehicleTransport
from routing.model.vehicle_section import VehicleSection


class TestVehicleSection(unittest.TestCase):
    """VehicleSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVehicleSection(self):
        """Test VehicleSection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VehicleSection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
