"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.distance import Distance
from routing.model.dynamic_speed_info import DynamicSpeedInfo
from routing.model.functional_class import FunctionalClass
from routing.model.localized_string import LocalizedString
from routing.model.max_speed import MaxSpeed
from routing.model.speed import Speed
globals()['Distance'] = Distance
globals()['DynamicSpeedInfo'] = DynamicSpeedInfo
globals()['FunctionalClass'] = FunctionalClass
globals()['LocalizedString'] = LocalizedString
globals()['MaxSpeed'] = MaxSpeed
globals()['Speed'] = Speed
from routing.model.pedestrian_span import PedestrianSpan


class TestPedestrianSpan(unittest.TestCase):
    """PedestrianSpan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPedestrianSpan(self):
        """Test PedestrianSpan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PedestrianSpan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
