"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.max_speed_one_of import MaxSpeedOneOf
globals()['MaxSpeedOneOf'] = MaxSpeedOneOf
from routing.model.max_speed import MaxSpeed


class TestMaxSpeed(unittest.TestCase):
    """MaxSpeed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMaxSpeed(self):
        """Test MaxSpeed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MaxSpeed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
