"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.avoid_post import AvoidPost
globals()['AvoidPost'] = AvoidPost
from routing.model.get_routes_by_handle_parameters import GetRoutesByHandleParameters


class TestGetRoutesByHandleParameters(unittest.TestCase):
    """GetRoutesByHandleParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetRoutesByHandleParameters(self):
        """Test GetRoutesByHandleParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetRoutesByHandleParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
