"""
    Routing API v8

    A location service providing customizable route calculations for a variety of vehicle types as well as pedestrian modes.  # noqa: E501

    The version of the OpenAPI document: 8.22.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import routing
from routing.model.access_point_place import AccessPointPlace


class TestAccessPointPlace(unittest.TestCase):
    """AccessPointPlace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessPointPlace(self):
        """Test AccessPointPlace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccessPointPlace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
